spring:
  datasource:
    url: jdbc:sqlserver://springsql.database.windows.net:1433;database=azure-springsql;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: springsql
    password: kgpco@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191


